### ISSUE TITLE
The code example integrating all the functions in the document cannot be executed.

### ISSUE THREAD

**Issue by MilkGe** [computed-axial-lithography/CAL-software#17]
When I run the reference code in the 'All together' section of the Example, it fails to execute (throws errors, Figure 1), indicating: 'Improper use of volshow>processParent: Figures created using the figure function do not support 3D rendering. Please use uifigure to create supported figures for 3D rendering.' 
fig1
![1713362341919](https://github.com/computed-axial-lithography/CAL-software-Matlab/assets/131436945/44e7c064-17fe-4019-b2d0-26466b83aa80)

I tried running the reference code separately in the 'Projection generation and optimization' section, and only the 2D matrix example was successful (no errors). The 3D matrix example and STL example both failed (Figure 2). I don't understand why this is happening.
@jttoombs 
fig2
![d7f1954f03731b01c152d78c913a8dc](https://github.com/computed-axial-lithography/CAL-software-Matlab/assets/131436945/11ba290b-53bb-498d-9032-676d01948f75)

**Comment by MilkGe** [comment]
I noted my matlab version is 2023a,which caused this error.Volshow function in 2023a is not applicable to 2019b developer use

**Comment by antoinexu** [comment]
Same issue. It is also not compatible with Matlab 2022b, maybe the volshow function in 2022b is also changing. When I got to 2019b, everything was fine.
